@echo off
echo Restarting n8n...
docker compose -f "%~dp0docker-compose.yml" restart n8n
echo Waiting for n8n to be ready...
timeout /t 15 /nobreak >nul
echo Toggling webhook...
node "%~dp0toggle_webhook.js"
pause
